apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.app.name}}
      app.kubernetes.io/component: {{.Values.app.component}}
      app.kubernetes.io/managed-by: {{.Values.app.manager}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.app.name}}
        app.kubernetes.io/component: {{.Values.app.component}}
        app.kubernetes.io/managed-by: {{.Values.app.manager}}
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command: ['sh', '-c',
            'until pg_isready -h postgres -p 5432;
          do echo waiting for database; sleep 10; done;']
      containers:
        - name: {{.Values.deployments.name}}
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.deployments.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.deployments.containerPort}}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          env:
            - name: POSTGRES_HOST
              value: postgres