apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\sburikova\Entwicklung\privat\otus\weather-application\kompose-windows-amd64.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: grafana
