spring:
  application:
    name: weather-service


api:
  key: change me
  base-url: http://api.weatherapi.com/v1
  method:
    current-weather: /current.json
    forecast: /forecast.json
    astronomy: /astronomy.json

