spring:
  application:
    name: weather-service
server:
  port: 9090


api:
  key: changeme
  base-url: http://api.weatherapi.com/v1
  method:
    current-weather: /current.json
    forecast: /forecast.json
    astronomy: /astronomy.json

