{
 "title": "4 golden signals",
 "description": "ОТУС Домашнее задание 15\n4 golden signals",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Traffic front api",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nTraffic (Rate)\n Объем трафика или какой-то объем нагрузки, который вы обрабатываете прямо сейчас, обычно это RPS, RPM и тд.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"frontapiservice:8080\", uri!~\".*actuator.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FRONT-API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"frontapiservice:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic weather-service",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nTraffic (Rate)\n Объем трафика или какой-то объем нагрузки, который вы обрабатываете прямо сейчас, обычно это RPS, RPM и тд.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"weatherservice:9890\", uri!~\".*actuator.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEATHER-SERVICE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"weatherservice:9890\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors front-api",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=\"frontapiservice:8080\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_server_requests_seconds_count{instance=\"frontapiservice:8080\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ARCHIVE-SERVICE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"archiveservice:9097\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Minute front-api",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nErrors\nЧастота ошибок или количество ошибок. Это могут быть некорректные коды ответа, исключения в приложении и тд. ",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=\"frontapiservice:8080\", status=\"500\"}[1m])) by (status) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Minute weather-service",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nErrors\nЧастота ошибок или количество ошибок. Это могут быть некорректные коды ответа, исключения в приложении и тд. ",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=\"weatherservice:9890\", status=\"500\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation archive-service",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nSaturation\nЭта метрика помогает отвечать на вопрос, на сколько загружено наше приложение. Допустим оно обрабатывает 150 запросов в секунду, а можем ли мы обработать 200 или 250 или мы уже загружены под 100% и больше не получится? Отметим, что многие приложения и системы деградируют еще сильно до того, как saturation достиг 100%. \n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(http_server_requests_seconds_count{instance=\"archiveservice:9097\", uri!~\".*actuator.*\"}[1m])) / max(rate(http_server_requests_seconds_count{instance=\"archiveservice:9097\", uri!~\".*actuator.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation weather-service",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nSaturation\nЭта метрика помогает отвечать на вопрос, на сколько загружено наше приложение. Допустим оно обрабатывает 150 запросов в секунду, а можем ли мы обработать 200 или 250 или мы уже загружены под 100% и больше не получится? Отметим, что многие приложения и системы деградируют еще сильно до того, как saturation достиг 100%. \n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(http_server_requests_seconds_count{instance=\"weatherservice:9890\", uri!~\".*actuator.*\"}[1m])) / max(rate(http_server_requests_seconds_count{instance=\"weatherservice:9890\", uri!~\".*actuator.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation front-api",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nSaturation\nЭта метрика помогает отвечать на вопрос, на сколько загружено наше приложение. Допустим оно обрабатывает 150 запросов в секунду, а можем ли мы обработать 200 или 250 или мы уже загружены под 100% и больше не получится? Отметим, что многие приложения и системы деградируют еще сильно до того, как saturation достиг 100%. \n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(http_server_requests_seconds_count{instance=\"frontapiservice:8080\", uri!~\".*actuator.*\"}[1m])) / max(rate(http_server_requests_seconds_count{instance=\"frontapiservice:8080\", uri!~\".*actuator.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}