{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Изменение температуры",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "temperature_point_feelsLike{instance=\"archiveservice:9097\",job=\"archiveservice\"}",
     "legendFormat": "feels like"
    },
    {
     "expr": "temperature_point{instance=\"archiveservice:9097\",job=\"archiveservice\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "Влажность воздуха",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "humidity_point{instance=\"archiveservice:9097\",job=\"archiveservice\"}",
     "legendFormat": "humidity"
    }
   ]
  },
  {
   "title": "Долгота дня",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "day_length{instance=\"archiveservice:9097\",job=\"archiveservice\"}",
     "legendFormat": "day length"
    }
   ]
  }
 ]
}