spring:
  application:
    name: archive-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9097
api:
  ip-address: changeme
service:
  weather:
    baseurl: http://weatherservice:9890/weather/service

management:
  endpoint:
    metrics:
      access: unrestricted
    health:
     access: unrestricted
    prometheus:
     access: unrestricted
  endpoints:
    web:
      exposure:
        include: info,prometheus

logging:
  level:
    sql: debug
    web: info