postgresql:
  fullnameOverride: postgres
  image:
    tag: 11.14.0-debian-10-r17
  auth:
    password: postgrespassword
    username: postgres
    database: postgres
  databasePort: 5432

  commonLabels:
    name: postgres
    component: database
    manager: helm
configmap:
  name: postgres-configmap

app:
  name: archive-service
  component: backend
  manager: helm

image:
  repository: samolet2415/archiveservice
  pullPolicy: Always
  tag: latest

deployments:
  name: app
  containerPort: 9097
  imagePullPolicy: Always

initContainers:
  name: check-db-ready
  image: postgres:9.6.5
  command: [ 'sh', '-c',
    'until pg_isready -h postgres -p 5432; 
            do echo waiting for database; sleep 5; done;' ]