spring:
  application:
    name: front-api

server:
  port: 8787

service:
  url: http://weatherchart.default.svc.cluster.local:9890/weather/service

management:
  endpoint:
    metrics:
      access: unrestricted
    health:
      access: unrestricted
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: info,prometheus
